name: Frontend Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Frontend Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js with a compatible version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0' # Use a compatible Node.js version for Next.js

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd aquatic-life
          npm install

      # Step 4: Run tests (if any)
      #- name: Run tests
       # run: |
       #   cd aquatic-life
         # npm test

      # Step 5: Build the frontend
      - name: Build frontend
        run: |
          cd aquatic-life
          npm run build
